CREATE TABLE T_HL_YW_HLJLWSSYB (
ID VARCHAR(32) NOT NULL
, BRID VARCHAR(32) NOT NULL
, WSID VARCHAR(32) NOT NULL
, HLDAFL VARCHAR(32)
, ZF NUMBER(5,2)
, JL VARCHAR(300)
, YLJGID VARCHAR(32) NOT NULL
, KSID VARCHAR(32) NOT NULL
, RQ DATETIME(0)
, QMYSID VARCHAR(32)
, DEL_FLAG VARCHAR(2) DEFAULT '0' NOT NULL
, CREATE_BY VARCHAR(32)
, CREATE_TIME DATETIME(0) DEFAULT SYSDATE NOT NULL
, UPDATE_BY VARCHAR(32)
, UPDATE_TIME DATETIME(0) DEFAULT SYSDATE NOT NULL
, REMARKS VARCHAR(255)
);
ALTER TABLE T_HL_YW_HLJLWSSYB ADD CONSTRAINT  T_HL_YW_HLJLWSSYB_PK PRIMARY KEY (id);
CREATE CLUSTER INDEX T_HL_YW_HLJLWSSYB_CLS ON T_HL_YW_HLJLWSSYB(brid);
COMMENT ON COLUMN T_HL_YW_HLJLWSSYB.ID IS '主键ID';
COMMENT ON COLUMN T_HL_YW_HLJLWSSYB.BRID IS '病人唯一号';
COMMENT ON COLUMN T_HL_YW_HLJLWSSYB.WSID IS '病历文书ID ';
COMMENT ON COLUMN T_HL_YW_HLJLWSSYB.HLDAFL IS '护理档案分类';
COMMENT ON COLUMN T_HL_YW_HLJLWSSYB.ZF IS '总分';
COMMENT ON COLUMN T_HL_YW_HLJLWSSYB.JL IS '结论';
COMMENT ON COLUMN T_HL_YW_HLJLWSSYB.YLJGID IS '医疗机构ID';
COMMENT ON COLUMN T_HL_YW_HLJLWSSYB.KSID IS '科室ID';
COMMENT ON COLUMN T_HL_YW_HLJLWSSYB.RQ IS '日期';
COMMENT ON COLUMN T_HL_YW_HLJLWSSYB.QMYSID IS '签名医生ID';
COMMENT ON COLUMN T_HL_YW_HLJLWSSYB.DEL_FLAG IS '删除标志';
COMMENT ON COLUMN T_HL_YW_HLJLWSSYB.CREATE_BY IS '创建人';
COMMENT ON COLUMN T_HL_YW_HLJLWSSYB.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN T_HL_YW_HLJLWSSYB.UPDATE_BY IS '更新人';
COMMENT ON COLUMN T_HL_YW_HLJLWSSYB.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN T_HL_YW_HLJLWSSYB.REMARKS IS '备注';
COMMENT ON TABLE T_HL_YW_HLJLWSSYB IS '病人护理记录单文书索引表';
