CREATE TABLE T_HL_DIC_HLJLWSXM (
ID VARCHAR(32) DEFAULT SYS_GUID() NOT NULL
, WSID VARCHAR(32) NOT NULL
, ZDLX VARCHAR(50) NOT NULL
, ZDLXMS VARCHAR(100)
, ZDXH NUMBER(3) NOT NULL
, ZDDM VARCHAR(50) NOT NULL
, ZDMC VARCHAR(300) NOT NULL
, FZ NUMBER(5,2)
, JB VARCHAR(100)
, DEL_FLAG VARCHAR(2) DEFAULT '0' NOT NULL
, CREATE_BY VARCHAR(32)
, CREATE_TIME DATETIME(0) DEFAULT SYSDATE NOT NULL
, UPDATE_BY VARCHAR(32)
, UPDATE_TIME DATETIME(0) DEFAULT SYSDATE NOT NULL
, REMARKS VARCHAR(255)
) STORAGE(FILLFACTOR 95, ON TS_HLYTH_KEEP);
ALTER TABLE T_HL_DIC_HLJLWSXM ADD CONSTRAINT  T_HL_DIC_HLJLWSXM_PK PRIMARY KEY (id);
CREATE CLUSTER INDEX T_HL_DIC_HLJLWSXM_CLS ON T_HL_DIC_HLJLWSXM(wsid);
COMMENT ON COLUMN T_HL_DIC_HLJLWSXM.ID IS '主键ID';
COMMENT ON COLUMN T_HL_DIC_HLJLWSXM.WSID IS '病历文书ID';
COMMENT ON COLUMN T_HL_DIC_HLJLWSXM.ZDLX IS '字典类型';
COMMENT ON COLUMN T_HL_DIC_HLJLWSXM.ZDLXMS IS '字典类型描述';
COMMENT ON COLUMN T_HL_DIC_HLJLWSXM.ZDXH IS '字典序号';
COMMENT ON COLUMN T_HL_DIC_HLJLWSXM.ZDDM IS '字典代码';
COMMENT ON COLUMN T_HL_DIC_HLJLWSXM.ZDMC IS '字典名称';
COMMENT ON COLUMN T_HL_DIC_HLJLWSXM.FZ IS '分值';
COMMENT ON COLUMN T_HL_DIC_HLJLWSXM.JB IS '级别';
COMMENT ON COLUMN T_HL_DIC_HLJLWSXM.DEL_FLAG IS '删除标志';
COMMENT ON COLUMN T_HL_DIC_HLJLWSXM.CREATE_BY IS '创建人';
COMMENT ON COLUMN T_HL_DIC_HLJLWSXM.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN T_HL_DIC_HLJLWSXM.UPDATE_BY IS '更新人';
COMMENT ON COLUMN T_HL_DIC_HLJLWSXM.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN T_HL_DIC_HLJLWSXM.REMARKS IS '备注';
COMMENT ON TABLE T_HL_DIC_HLJLWSXM IS '护理记录单文书项目字典';
