CREATE TABLE T_HL_DIC_HLDAFLWSDZ (
ID VARCHAR(32) NOT NULL
, WSID VARCHAR(32) NOT NULL
, HLDAFL VARCHAR(32) NOT NULL
, XH NUMBER(2) NOT NULL
, DEL_FLAG VARCHAR(2) DEFAULT '0' NOT NULL
, CREATE_BY VARCHAR(32)
, CREATE_TIME DATETIME(0) DEFAULT SYSDATE NOT NULL
, UPDATE_BY VARCHAR(32)
, UPDATE_TIME DATETIME(0) DEFAULT SYSDATE NOT NULL
, REMARKS VARCHAR(255)
);
ALTER TABLE T_HL_DIC_HLDAFLWSDZ ADD CONSTRAINT  T_HL_DIC_HLDAFLWSDZ_PK PRIMARY KEY (id);
CREATE CLUSTER INDEX T_HL_DIC_HLDAFLWSDZ_CLS ON T_HL_DIC_HLDAFLWSDZ(hldafl);
COMMENT ON COLUMN T_HL_DIC_HLDAFLWSDZ.ID IS '主键ID';
COMMENT ON COLUMN T_HL_DIC_HLDAFLWSDZ.WSID IS '病历文书ID';
COMMENT ON COLUMN T_HL_DIC_HLDAFLWSDZ.HLDAFL IS '护理档案分类';
COMMENT ON COLUMN T_HL_DIC_HLDAFLWSDZ.XH IS '序号';
COMMENT ON COLUMN T_HL_DIC_HLDAFLWSDZ.DEL_FLAG IS '删除标志';
COMMENT ON COLUMN T_HL_DIC_HLDAFLWSDZ.CREATE_BY IS '创建人';
COMMENT ON COLUMN T_HL_DIC_HLDAFLWSDZ.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN T_HL_DIC_HLDAFLWSDZ.UPDATE_BY IS '更新人';
COMMENT ON COLUMN T_HL_DIC_HLDAFLWSDZ.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN T_HL_DIC_HLDAFLWSDZ.REMARKS IS '备注';
COMMENT ON TABLE T_HL_DIC_HLDAFLWSDZ IS '护理档案分类记录文书对照表';
