CREATE TABLE T_HL_YW_HLXM_PGJY (
ID VARCHAR(32) NOT NULL
, PGID VARCHAR(32) NOT NULL
, BRID VARCHAR(32) NOT NULL
, HLXMID VARCHAR(32) NOT NULL
, HLXMMC VARCHAR(200)
, HLCS NUMBER(3)
, HLPC VARCHAR(20)
, HLJE NUMBER(10,2)
, HLXQ VARCHAR(200)
, YLJGID VARCHAR(32)
, SQKSID VARCHAR(32)
, SQYSID VARCHAR(32)
, DEL_FLAG VARCHAR(2) DEFAULT '0' NOT NULL
, CREATE_BY VARCHAR(32)
, CREATE_TIME DATETIME(0) DEFAULT SYSDATE NOT NULL
, UPDATE_BY VARCHAR(32)
, UPDATE_TIME DATETIME(0) DEFAULT SYSDATE NOT NULL
, REMARKS VARCHAR(255)
);
ALTER TABLE T_HL_YW_HLXM_PGJY ADD CONSTRAINT  T_HL_YW_HLXM_PGJY_PK PRIMARY KEY (id);
CREATE INDEX T_HL_YW_HLXM_PGJY_IDX1 ON T_HL_YW_HLXM_PGJY(brid);
CREATE CLUSTER INDEX T_HL_YW_HLXM_PGJY_CLS ON T_HL_YW_HLXM_PGJY(pgid);
COMMENT ON COLUMN T_HL_YW_HLXM_PGJY.ID IS '主键ID';
COMMENT ON COLUMN T_HL_YW_HLXM_PGJY.PGID IS '评估唯一号';
COMMENT ON COLUMN T_HL_YW_HLXM_PGJY.BRID IS '病人唯一号';
COMMENT ON COLUMN T_HL_YW_HLXM_PGJY.HLXMID IS '护理项目ID';
COMMENT ON COLUMN T_HL_YW_HLXM_PGJY.HLXMMC IS '护理项目名称';
COMMENT ON COLUMN T_HL_YW_HLXM_PGJY.HLCS IS '护理次数';
COMMENT ON COLUMN T_HL_YW_HLXM_PGJY.HLPC IS '护理频次';
COMMENT ON COLUMN T_HL_YW_HLXM_PGJY.HLJE IS '护理金额';
COMMENT ON COLUMN T_HL_YW_HLXM_PGJY.HLXQ IS '护理需求';
COMMENT ON COLUMN T_HL_YW_HLXM_PGJY.YLJGID IS '医疗机构ID';
COMMENT ON COLUMN T_HL_YW_HLXM_PGJY.SQKSID IS '医嘱科室ID';
COMMENT ON COLUMN T_HL_YW_HLXM_PGJY.SQYSID IS '医嘱医生ID';
COMMENT ON COLUMN T_HL_YW_HLXM_PGJY.DEL_FLAG IS '删除标志';
COMMENT ON COLUMN T_HL_YW_HLXM_PGJY.CREATE_BY IS '创建人';
COMMENT ON COLUMN T_HL_YW_HLXM_PGJY.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN T_HL_YW_HLXM_PGJY.UPDATE_BY IS '更新人';
COMMENT ON COLUMN T_HL_YW_HLXM_PGJY.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN T_HL_YW_HLXM_PGJY.REMARKS IS '备注';
COMMENT ON TABLE T_HL_YW_HLXM_PGJY IS '病人护理项目评估建议';
