CREATE TABLE T_HL_YW_CXTTPGB_CFYSYQK (
ID VARCHAR(32) NOT NULL
, BLWSID VARCHAR(32) NOT NULL
, YWMC VARCHAR(50) NOT NULL
, FYJL VARCHAR(10) NOT NULL
, FYSJ VARCHAR(20) NOT NULL
, FYTJ VARCHAR(20) NOT NULL
);
ALTER TABLE T_HL_YW_CXTTPGB_CFYSYQK ADD CONSTRAINT  T_HL_YW_CXTTPGB_CFYS_PK PRIMARY KEY (id);
CREATE CLUSTER INDEX T_HL_YW_CXTTPGB_CFYS_CLS ON T_HL_YW_CXTTPGB_CFYSYQK(blwsid);
COMMENT ON COLUMN T_HL_YW_CXTTPGB_CFYSYQK.ID IS '主键ID';
COMMENT ON COLUMN T_HL_YW_CXTTPGB_CFYSYQK.BLWSID IS '病人文书索引唯一键';
COMMENT ON COLUMN T_HL_YW_CXTTPGB_CFYSYQK.YWMC IS '药物名称';
COMMENT ON COLUMN T_HL_YW_CXTTPGB_CFYSYQK.FYJL IS '剂量';
COMMENT ON COLUMN T_HL_YW_CXTTPGB_CFYSYQK.FYSJ IS '时间';
COMMENT ON COLUMN T_HL_YW_CXTTPGB_CFYSYQK.FYTJ IS '途径';
COMMENT ON TABLE T_HL_YW_CXTTPGB_CFYSYQK IS '持续疼痛评估表_处方药使用情况';
