CREATE TABLE T_HL_YW_MZFHLJLD_WHXR (
ID VARCHAR(32) NOT NULL
, BLWSID VARCHAR(32) NOT NULL
, YWMC VARCHAR(50) NOT NULL
, FYCS NUMBER(2) NOT NULL
, HZFY VARCHAR(200) NOT NULL
);
ALTER TABLE T_HL_YW_MZFHLJLD_WHXR ADD CONSTRAINT  T_HL_YW_MZFHLJLD_WHX_PK PRIMARY KEY (id);
CREATE CLUSTER INDEX T_HL_YW_MZFHLJLD_WHX_CLS ON T_HL_YW_MZFHLJLD_WHXR(blwsid);
COMMENT ON COLUMN T_HL_YW_MZFHLJLD_WHXR.ID IS '主键ID';
COMMENT ON COLUMN T_HL_YW_MZFHLJLD_WHXR.BLWSID IS '病人文书索引唯一键';
COMMENT ON COLUMN T_HL_YW_MZFHLJLD_WHXR.YWMC IS '药物名称';
COMMENT ON COLUMN T_HL_YW_MZFHLJLD_WHXR.FYCS IS '次数';
COMMENT ON COLUMN T_HL_YW_MZFHLJLD_WHXR.HZFY IS '患者反应';
COMMENT ON TABLE T_HL_YW_MZFHLJLD_WHXR IS '慢阻肺护理记录单_雾化吸入';
