CREATE TABLE T_HL_YW_HLJLMX (
ID VARCHAR(32) NOT NULL
, BLWSID VARCHAR(32) NOT NULL
, XMDM VARCHAR(100) NOT NULL
, XMMC VARCHAR(300) NOT NULL
, XMZSM VARCHAR(300) NOT NULL
, XMZ VARCHAR NOT NULL
, FZ NUMBER(5,2)
, BZ VARCHAR(200)
);
ALTER TABLE T_HL_YW_HLJLMX ADD CONSTRAINT  T_HL_YW_HLJLMX_PK PRIMARY KEY (id);
CREATE CLUSTER INDEX T_HL_YW_HLJLMX_CLS ON T_HL_YW_HLJLMX(blwsid);
COMMENT ON COLUMN T_HL_YW_HLJLMX.ID IS '主键ID';
COMMENT ON COLUMN T_HL_YW_HLJLMX.BLWSID IS '病人文书索引唯一键';
COMMENT ON COLUMN T_HL_YW_HLJLMX.XMDM IS '项目代码';
COMMENT ON COLUMN T_HL_YW_HLJLMX.XMMC IS '项目名称';
COMMENT ON COLUMN T_HL_YW_HLJLMX.XMZSM IS '项目值说明';
COMMENT ON COLUMN T_HL_YW_HLJLMX.XMZ IS '项目值';
COMMENT ON COLUMN T_HL_YW_HLJLMX.FZ IS '分值';
COMMENT ON COLUMN T_HL_YW_HLJLMX.BZ IS '备注';
COMMENT ON TABLE T_HL_YW_HLJLMX IS '病人护理记录单明细项表';
