CREATE TABLE T_HL_DIC_HLJLWS (
ID VARCHAR(32) DEFAULT SYS_GUID() NOT NULL
, MC VARCHAR(200) NOT NULL
, XH NUMBER(4) NOT NULL
, FL VARCHAR(32) NOT NULL
, FLDM VARCHAR(32) NOT NULL
, FLXH NUMBER(4) NOT NULL
, BBH NUMBER(5,2) NOT NULL
, URL VARCHAR(128)
, LX VARCHAR(2)
, LBLX VARCHAR(2)
, QTBJ VARCHAR(1) DEFAULT '0' NOT NULL
, QYRQ DATETIME(0)
, TYRQ DATETIME(0)
, DEL_FLAG VARCHAR(2) DEFAULT '0' NOT NULL
, CREATE_BY VARCHAR(32)
, CREATE_TIME DATETIME(0) DEFAULT SYSDATE NOT NULL
, UPDATE_BY VARCHAR(32)
, UPDATE_TIME DATETIME(0) DEFAULT SYSDATE NOT NULL
, REMARKS VARCHAR(255)
) STORAGE(FILLFACTOR 95, ON TS_HLYTH_KEEP);
ALTER TABLE T_HL_DIC_HLJLWS ADD CONSTRAINT  T_HL_DIC_HLJLWS_PK PRIMARY KEY (id);
COMMENT ON COLUMN T_HL_DIC_HLJLWS.ID IS '主键ID';
COMMENT ON COLUMN T_HL_DIC_HLJLWS.MC IS '文书名称';
COMMENT ON COLUMN T_HL_DIC_HLJLWS.XH IS '文书序号';
COMMENT ON COLUMN T_HL_DIC_HLJLWS.FL IS '文书分类名称';
COMMENT ON COLUMN T_HL_DIC_HLJLWS.FLDM IS '文书分类代码';
COMMENT ON COLUMN T_HL_DIC_HLJLWS.FLXH IS '文书分类序号';
COMMENT ON COLUMN T_HL_DIC_HLJLWS.BBH IS '版本号';
COMMENT ON COLUMN T_HL_DIC_HLJLWS.URL IS '系统关联页面ID（关联菜单信息表通过菜单表进行授权使用）';
COMMENT ON COLUMN T_HL_DIC_HLJLWS.LX IS '文书类型';
COMMENT ON COLUMN T_HL_DIC_HLJLWS.LBLX IS '量表类型';
COMMENT ON COLUMN T_HL_DIC_HLJLWS.QTBJ IS '启停标记';
COMMENT ON COLUMN T_HL_DIC_HLJLWS.QYRQ IS '启用日期';
COMMENT ON COLUMN T_HL_DIC_HLJLWS.TYRQ IS '停用日期';
COMMENT ON COLUMN T_HL_DIC_HLJLWS.DEL_FLAG IS '删除标志';
COMMENT ON COLUMN T_HL_DIC_HLJLWS.CREATE_BY IS '创建人';
COMMENT ON COLUMN T_HL_DIC_HLJLWS.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN T_HL_DIC_HLJLWS.UPDATE_BY IS '更新人';
COMMENT ON COLUMN T_HL_DIC_HLJLWS.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN T_HL_DIC_HLJLWS.REMARKS IS '备注';
COMMENT ON TABLE T_HL_DIC_HLJLWS IS '护理记录单文书字典';
